"""Peer-review-ready data acquisition narrative for the TRGB comparative pipeline.

Produces a single ``data_acquisition_narrative.md`` in the pipeline's
reports directory documenting how every astronomical dataset used in
the analysis was obtained: source URLs, transcription protocol,
SHA-256 file manifests, spot-check verifications, calibrator-coverage
audit results, and reproducibility instructions for an external
reviewer to retrieve the data deterministically.

The narrative is regenerated by the standard pipeline run (called from
:py:meth:`TRGBComparativePipeline.run`) so SHA-256 values and file
counts always reflect the current contents of ``trgb_data/catalogs/`` and
``downloaded_data/``.
"""

from __future__ import annotations

import hashlib
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional

logger = logging.getLogger(__name__)


# =============================================================================
# Helpers
# =============================================================================


def _sha256(path: Path) -> str:
    """Return the SHA-256 hex digest of a file (or '<missing>' if absent)."""
    if not path.exists():
        return "<missing>"
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _short_sha(s: str, n: int = 16) -> str:
    if not isinstance(s, str) or len(s) < n:
        return s
    return s[:n]


def _now() -> str:
    return datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def _line_count(path: Path) -> int:
    if not path.exists():
        return 0
    return sum(1 for _ in path.open("rb"))


def _file_size_human(path: Path) -> str:
    if not path.exists():
        return "—"
    size = path.stat().st_size
    for unit in ("B", "kB", "MB", "GB"):
        if size < 1024:
            return f"{size:.1f} {unit}"
        size /= 1024
    return f"{size:.1f} TB"


# =============================================================================
# Section renderers
# =============================================================================


def _section_overview() -> str:
    return (
        "## 1. Overview\n\n"
        "The TRGB comparative pipeline tests the H-ΛCDM holographic projection "
        "formula against two independent reproductions of recent CCHP TRGB "
        "Hubble-constant measurements: Freedman et al. 2019 (LMC-anchored, "
        "ApJ 882, 34) and Freedman et al. 2025 (NGC 4258-anchored, ApJ 985, "
        "203). Each reproduction is performed against four independent SN Ia "
        "photometric systems (CSP-I, CSP-II, SuperCal, Pantheon+SH0ES) plus "
        "a JWST-only sensitivity variant of Case B. All data sources are "
        "public; this document records exactly which file (with SHA-256) "
        "was used for each.\n\n"
        "Source-hierarchy policy followed throughout acquisition:\n\n"
        "1. Author-provided machine-readable archive (GitHub, VizieR, ApJ "
        "supplementary materials).\n"
        "2. arXiv source tarball (`e-print` retrieval) when point 1 is "
        "incomplete; transcribe LaTeX deluxetables verbatim.\n"
        "3. PDF transcription only when neither 1 nor 2 yields the table; "
        "with paper spot-checks recorded in the CSV header.\n"
        "4. Direct correspondence with authors only as a documented "
        "last resort (not used in the analysis as published).\n\n"
        "Every transcribed table carries a comment block listing the "
        "source paper, DOI / arXiv identifier, transcription date, and "
        "spot-check verifications against the published values.\n\n"
    )


def _section_anchors(loader) -> str:
    lines = ["## 2. Geometric distance anchors\n\n"]

    try:
        lmc = loader.load_pietrzynski_lmc_distance()
        lines.append(
            f"### 2.1 LMC eclipsing-binary distance (Case A)\n\n"
            f"- **Source**: Pietrzyński et al. 2019, Nature 567, 200, "
            f"DOI [10.1038/s41586-019-0999-4](https://doi.org/10.1038/s41586-019-0999-4), "
            f"arXiv:1903.08096.\n"
            f"- **Quantity**: μ_LMC = {lmc['mu']} ± {lmc['sigma_mu_stat']} (stat) "
            f"± {lmc['sigma_mu_sys']} (sys) mag, "
            f"d = {lmc.get('d_kpc', '?')} kpc.\n"
            f"- **Acquisition**: encoded as constants in "
            f"`DataLoader.load_pietrzynski_lmc_distance()` because the "
            f"published value is a single scalar with negligible per-paper "
            f"variance. No machine-readable archive is needed; the value "
            f"is paper-traceable to one decimal of precision in the "
            f"abstract. The pipeline's data-tables LaTeX file ("
            f"`results/trgb_comparative/reports/data_tables.tex` Table 1) "
            f"reproduces the value with citation.\n\n"
        )
    except Exception as exc:
        lines.append(f"_(LMC anchor unavailable: {exc})_\n\n")

    try:
        ngc = loader.load_reid_ngc4258_distance()
        lines.append(
            f"### 2.2 NGC 4258 maser distance (Case B)\n\n"
            f"- **Source**: Reid et al. 2019, ApJL 886, L27, "
            f"DOI [10.3847/2041-8213/ab552d](https://doi.org/10.3847/2041-8213/ab552d), "
            f"arXiv:1908.05625.\n"
            f"- **Quantity**: μ_N4258 = {ngc['mu']} ± {ngc['sigma_mu_stat']} (stat) "
            f"± {ngc['sigma_mu_sys']} (sys) mag, "
            f"d = {ngc.get('d_mpc', '?')} Mpc.\n"
            f"- **Acquisition**: same convention as LMC — encoded as "
            f"constants in the loader. The Reid et al. distance is the "
            f"VLBI maser-derived value; no community-standard machine-"
            f"readable catalog exists.\n\n"
        )
    except Exception as exc:
        lines.append(f"_(NGC 4258 anchor unavailable: {exc})_\n\n")

    return "".join(lines)


def _section_trgb_tables(loader) -> str:
    lines = ["## 3. TRGB calibrator distance tables (Freedman et al.)\n\n"]
    lines.append(
        "Three calibrator distance tables drive the chain matrix. All three "
        "are transcribed verbatim from the published source — Freedman et al. "
        "2019 from the journal PDF (no arXiv source LaTeX was present at "
        "transcription time); Freedman et al. 2025 from the arXiv source "
        "LaTeX (`Ho2024.tex`, retrieved from arxiv.org/e-print/2408.06153). "
        "Each transcription CSV carries a comment-block header documenting "
        "the source, transcription date, and spot-check verifications "
        "against the paper.\n\n"
    )

    f19_t1_path = Path("trgb_data/catalogs/freedman_2019_table1.csv")
    f19_t3_path = Path("trgb_data/catalogs/freedman_2019_table3.csv")
    f25_t2_path = Path("trgb_data/catalogs/freedman_2025_table2.csv")
    f25_t3_path = Path("trgb_data/catalogs/freedman_2025_table3.csv")

    lines.append(
        "| Table | Source paper | Source format | Transcription path | "
        "Lines | SHA-256 (first 16) |\n"
        "| --- | --- | --- | --- | ---: | --- |\n"
    )
    for label, src_paper, src_fmt, p in [
        ("F2019 Table 1 (per-host A_F814W)",
         "Freedman et al. 2019, ApJ 882, 34",
         "PDF transcription",
         f19_t1_path),
        ("F2019 Table 3 (TRGB calibrators, full)",
         "Freedman et al. 2019, ApJ 882, 34",
         "PDF transcription",
         f19_t3_path),
        ("F2025 Table 2 (JWST 11-SN)",
         "Freedman et al. 2025, ApJ 985, 203",
         "arXiv 2408.06153 LaTeX source",
         f25_t2_path),
        ("F2025 Table 3 (augmented HST+JWST 24-SN)",
         "Freedman et al. 2025, ApJ 985, 203",
         "arXiv 2408.06153 LaTeX source",
         f25_t3_path),
    ]:
        sha = _sha256(p)
        lines.append(
            f"| {label} | {src_paper} | {src_fmt} | "
            f"`{p}` | {_line_count(p)} | "
            f"`{_short_sha(sha)}…` |\n"
        )
    lines.append("\n")

    lines.append(
        "**Spot-check verifications** (recorded in each CSV's comment "
        "header, executed during transcription):\n\n"
        "- F2019 Table 3: SN 2012fr / NGC 1365 with `m_B^CSP = 12.09`, "
        "`m_B^SC = 11.92`; SN 1981B / NGC 4536 with `m_B^CSP = 11.64`, "
        "`m_B^SC = 11.62`; SN 2011fe / M101 with `m_B^CSP = 9.82`, "
        "`m_B^SC = 9.75`. Values match the published paper to two decimal "
        "places.\n"
        "- F2025 Table 2: SN 2012fr / NGC 1365 with `μ_TRGB = 31.366`, "
        "`μ_JAGB = 31.384`; SN 1981B / NGC 4536 with `μ_TRGB = 30.923`, "
        "`μ_JAGB = 30.971`. Values match the LaTeX source verbatim.\n"
        "- F2025 Table 3: SN 2011fe / M101 with `μ_TRGB^CCHP = 29.113`; "
        "SN 1990N / NGC 4639 with `μ_TRGB^CCHP = 31.774`. Verbatim from "
        "LaTeX source.\n\n"
        "**Critical methodology note** — Case B target H₀ comes from "
        "F2025 Table 3, NOT Table 2. The published TRGB H₀ = 70.39 ± 1.22 "
        "(stat) ± 1.33 (sys) is derived from the 24-SN augmented HST+JWST "
        "calibrator sample (F2025 Table 4 / `tab:hovalues` row "
        "\"24 SN calibrators, z>0.01; pymc\"), not the 11-SN JWST-only "
        "Table 2 subset (which gives 68.81 ± 1.80). The pipeline's "
        "primary Case B chains use Table 3; the JWST-only chain is a "
        "labelled sensitivity variant.\n\n"
    )
    return "".join(lines)


def _section_sn_samples(loader) -> str:
    lines = ["## 4. SN Ia photometric sample catalogs\n\n"]
    lines.append(
        "Three independent SN Ia photometric system catalogs feed the four "
        "per-system MCMC chains: Uddin 2024 h0csp (CSP-I + CSP-II native "
        "Carnegie photometry), Pantheon 2018 (Scolnic 2018; SuperCal-system "
        "foundation), and Pantheon+SH0ES (Brout 2022). Each catalog was "
        "obtained from the authors' public repository or supplementary "
        "archive; no PDF transcriptions are involved at this layer.\n\n"
    )

    # Uddin 2024 h0csp
    uddin_dir = Path("trgb_data/downloaded_data/uddin_h0csp")
    flow = uddin_dir / "B_all_noj21.csv"
    cal_f19 = uddin_dir / "calibrators_trgb_f19.csv"
    cal_full = uddin_dir / "calibrators_trgb.csv"
    trgb_unified = uddin_dir / "B_trgb_update3.csv"
    lines.append(
        "### 4.1 Uddin 2024 h0csp B-band SN Ia sample\n\n"
        "- **Source**: Uddin, S. A., Burns, C. R., Phillips, M. M., et al. "
        "2024, ApJ 970, 72, "
        "DOI [10.3847/1538-4357/ad53c3](https://doi.org/10.3847/1538-4357/ad53c3), "
        "arXiv:2308.01875.\n"
        "- **Public archive**: "
        "[github.com/syeduddin/h0csp](https://github.com/syeduddin/h0csp) "
        "(public companion repository).\n"
        "- **Acquisition**: cloned via `git clone --depth 1` on 2026-04-24; "
        "files staged into `trgb_data/downloaded_data/uddin_h0csp/` with SHA-256 "
        "manifests written to `PROVENANCE.md` in the same directory.\n"
        "- **Files used**:\n\n"
        "  | File | Rows | Size | SHA-256 (first 16) |\n"
        "  | --- | ---: | ---: | --- |\n"
    )
    for label, p in [
        ("`B_all_noj21.csv` (full 390-SN flow + flagged calibrators)", flow),
        ("`calibrators_trgb_f19.csv` (18-SN F2019-style TRGB cal subset)", cal_f19),
        ("`calibrators_trgb.csv` (20-SN expanded TRGB cal set)", cal_full),
        ("`B_trgb_update3.csv` (unified Hubble-diagram input file used by Uddin's H0CSP.py)", trgb_unified),
    ]:
        lines.append(
            f"  | {label} | {_line_count(p) - 1} | "
            f"{_file_size_human(p)} | `{_short_sha(_sha256(p))}…` |\n"
        )
    lines.append(
        "\n- **Likelihood reproduction**: the pipeline's "
        "`uddin_csp_chain.py` implements Uddin 2023's exact 8-parameter "
        "SNooPy log-likelihood (form from `scripts/H0CSP.py:like` in "
        "the source repository). The Uddin 2023 positive-control test "
        "(`run_uddin_positive_control` in `trgb_pipeline.py`) reproduces "
        "Uddin's published H₀ = 70.242 ± 0.724 within ±0.1 km/s/Mpc, "
        "validating that our likelihood implementation is faithful to "
        "the original.\n\n"
    )

    # Pantheon 2018
    p18 = Path("downloaded_data/pantheon_2018/lcparam_full_long.txt")
    lines.append(
        "### 4.2 Pantheon 2018 cosmology sample (Scolnic et al. 2018)\n\n"
        "- **Source**: Scolnic, D. M., Jones, D. O., Rest, A., et al. "
        "2018, ApJ 859, 101, "
        "DOI [10.3847/1538-4357/aab9bb](https://doi.org/10.3847/1538-4357/aab9bb), "
        "arXiv:1710.00845.\n"
        "- **Public archive**: "
        "[github.com/dscolnic/Pantheon](https://github.com/dscolnic/Pantheon).\n"
        "- **File**: `lcparam_full_long.txt` ("
        f"{_line_count(p18) - 1} SNe Ia, "
        f"{_file_size_human(p18)}, SHA-256 `{_short_sha(_sha256(p18))}…`).\n"
        "- **Acquisition**: `urllib` retrieval to "
        "`downloaded_data/pantheon_2018/` on first call to "
        "`DataLoader.load_pantheon_2018()`. Subsequent calls read the "
        "cached file. SHA-256 computed at every load and reported in "
        "the loader's return dict (`file_sha256` key).\n"
        "- **Photometric foundation**: Pantheon 2018 uses the Scolnic "
        "et al. 2015 SuperCal cross-calibration (DOI "
        "[10.1088/0004-637X/815/2/117](https://doi.org/10.1088/0004-637X/815/2/117)). "
        "Our SuperCal chain therefore pairs F2019 Table 3 m_B^SC values "
        "(for calibrators) with Pantheon 2018 `mb` values (for the "
        "Hubble flow).\n"
        "- **Critical limitation**: Pantheon 2018 explicitly excludes "
        "nearby calibrators (every SN with z_CMB < 0.01) — see "
        "`host_coverage_limitations.md` §1. The SuperCal-chain calibrator "
        "magnitudes therefore must come from F2019 Table 3, not from "
        "this catalog directly.\n\n"
    )

    # Pantheon+SH0ES
    pp = Path("downloaded_data/pantheon_plus/Pantheon+SH0ES.dat")
    lines.append(
        "### 4.3 Pantheon+SH0ES (Brout et al. 2022)\n\n"
        "- **Source**: Brout, D., Scolnic, D., Popovic, B., et al. 2022, "
        "ApJ 938, 110, "
        "DOI [10.3847/1538-4357/ac8e04](https://doi.org/10.3847/1538-4357/ac8e04), "
        "arXiv:2202.04077.\n"
        "- **Public archive**: "
        "[github.com/PantheonPlusSH0ES/DataRelease](https://github.com/PantheonPlusSH0ES/DataRelease).\n"
        f"- **File**: `Pantheon+SH0ES.dat` ({_line_count(pp) - 1} rows, "
        f"{_file_size_human(pp)}, SHA-256 `{_short_sha(_sha256(pp))}…`). "
        "Companion covariance file `Pantheon+SH0ES_STAT+SYS.cov` co-located.\n"
        "- **Acquisition**: cloned alongside the Pantheon 2018 retrieval; "
        "loaded by `DataLoader.load_pantheon_plus()`.\n"
        "- **Calibrator audit (2026-04-25)**: Pantheon+'s `IS_CALIBRATOR=1` "
        "flag tracks \"has R22 Cepheid distance\" and is orthogonal to "
        "our TRGB-anchored analysis. The pipeline's `build_pantheon_plus"
        "_inputs_full` factory matches Pantheon+ rows to the requested "
        "calibrator sample by CID with photometry-source-suffix tolerance "
        "(e.g. `1994DRichmond` → `1994D`) and does **not** require "
        "IS_CALIBRATOR=1. See `host_coverage_audit.md` for the per-SN "
        "audit trail and `host_coverage_limitations.md` for the 2 "
        "remaining genuinely-absent calibrators (1989B, 1998bu).\n\n"
    )
    return "".join(lines)


def _section_hoyt(loader) -> str:
    lines = ["## 5. SN-system H₀ recalibrations (Hoyt et al. 2025)\n\n"]
    hoyt_path = Path("trgb_data/catalogs/hoyt_2025_tables.csv")
    lines.append(
        "- **Source**: Hoyt, T. J., Jang, I.-S., Freedman, W. L., et al. "
        "2025, arXiv:2503.11769 (preprint as of acquisition; expected to "
        "appear in ApJ).\n"
        "- **Acquisition**: arXiv source LaTeX retrieved on 2026-04-24 via "
        "`curl -L https://arxiv.org/e-print/2503.11769`. The combined "
        "Tables 6 + 7 (`tab:trgb_sn_cal` in `trgb_sncal_v01-27-25.tex`) "
        "transcribed verbatim into "
        f"[`{hoyt_path}`]({hoyt_path}) "
        f"({_line_count(hoyt_path) - 1} rows including header comments, "
        f"SHA-256 `{_short_sha(_sha256(hoyt_path))}…`).\n"
        "- **Spot-check verifications** (recorded in CSV header): CSP-I "
        "row `H0_ref = 69.8` and `augmented_H0 = 69.73`; Pantheon+ row "
        "`H0_ref = 73.04` and `augmented_H0 = 71.62`. Values match the "
        "paper text and Table 7 verbatim.\n"
        "- **Pipeline usage**: The Hoyt 2025 per-SN-system H₀ values are "
        "used **only** as a literature cross-reference for the analysis "
        "report's chain matrix. They are **not** substituted into any "
        "MCMC-named field. Per-pipeline discipline (codified in the "
        "Stage 1 preregistration amendment): all chain-matrix `H0_median` "
        "values are pipeline-computed MCMC posteriors; Hoyt-derived "
        "values live in `literature_citations` dicts with explicit "
        "`nature: literature_citation_not_pipeline_mcmc` tags.\n\n"
    )
    return "".join(lines)


def _section_auxiliary() -> str:
    lines = ["## 6. Auxiliary datasets (not used in primary chains)\n\n"]
    lines.append(
        "Two additional datasets are loaded by the pipeline for diagnostic "
        "or cross-check purposes; they do not enter the primary H₀ "
        "posterior. Listed here for completeness so reviewers can verify "
        "the full data inventory.\n\n"
    )
    anand = Path("trgb_data/downloaded_data/trgb/anand2022_catalog.csv")
    if anand.exists():
        lines.append(
            "### 6.1 Anand et al. 2022 TRGB distance catalog\n\n"
            "- **Source**: Anand, G. S., Tully, R. B., Rizzi, L., Riess, "
            "A. G., & Yuan, W. 2022, ApJ 932, 15, "
            "DOI [10.3847/1538-4357/ac68df](https://doi.org/10.3847/1538-4357/ac68df), "
            "arXiv:2108.00007.\n"
            "- **Public archive**: Extragalactic Distance Database (EDD) "
            "[edd.ifa.hawaii.edu](http://edd.ifa.hawaii.edu).\n"
            f"- **File**: `{anand}` "
            f"(SHA-256 `{_short_sha(_sha256(anand))}…`).\n"
            "- **Pipeline usage**: alternative TRGB distance source for "
            "sensitivity testing, selectable via the `tip_source='anand_2022'` "
            "argument on `data_loaders.load_case_a()` / `load_case_b()`. "
            "Not used in the primary chain matrix; the primary matrix uses "
            "Freedman 2019 / 2025 distances directly.\n\n"
        )

    lmc_phot = Path("trgb_data/downloaded_data/trgb/lmc_hatt2018_halo_photometry.csv")
    if lmc_phot.exists():
        lines.append(
            "### 6.2 LMC halo-field HST photometry (Hatt et al. 2018)\n\n"
            f"- **File**: `{lmc_phot}` "
            f"(SHA-256 `{_short_sha(_sha256(lmc_phot))}…`).\n"
            "- **Source**: Hatt, D., Beaton, R. L., Freedman, W. L., et al. "
            "2018, ApJ 861, 104, DOI 10.3847/1538-4357/aac9b9, "
            "arXiv:1806.02901.\n"
            "- **Pipeline usage**: synthetic photometry stub used by the "
            "edge-detection diagnostic plots. Not part of the H₀ derivation; "
            "the published μ_TRGB is taken from the Pietrzyński 2019 anchor "
            "value rather than re-derived from these photometry stubs.\n\n"
        )
    return "".join(lines)


def _section_audit_summary() -> str:
    return (
        "## 7. Data-acquisition audit trail\n\n"
        "Two adversarial audits have been performed against the data "
        "acquisition layer:\n\n"
        "### 7.1 Verification audit (2026-04-24)\n\n"
        "Checked that every reported H₀ value traces to a pipeline-"
        "computed MCMC posterior (not a literature citation), that data "
        "loaders return real data (not stubs), that chain SHA-256s "
        "match the staged data files, and that no override pattern "
        "silently substitutes literature values into reproduction-named "
        "fields. Result: PASS on all 12 verification requirements; six "
        "non-critical issues documented. Full report: "
        "[`verification_audit.md`](verification_audit.md).\n\n"
        "### 7.2 Host-coverage audit (2026-04-25)\n\n"
        "Investigated SuperCal and Pantheon+ chains operating with "
        "fewer calibrators than CSP chains (14/24 vs 24/24 for "
        "SuperCal; 16/24 vs 24/24 for Pantheon+ in Case B). Per-SN "
        "categorization:\n\n"
        "- **Category A** (genuine catalog absence): 20 (host, SN, "
        "chain) tuples. SuperCal cannot include the 10 missing SNe "
        "because F2019 Table 3 does not list `m_B^SuperCal` for them "
        "(the Scolnic 2015 cross-cal anchor required Cepheid distances, "
        "and the missing hosts have none). Hoyt 2025 Table I "
        "`augmented_N=14` independently confirms our SuperCal sample "
        "size. Pantheon+ does not include 1989B and 1998bu at all.\n"
        "- **Category B** (parser bug): 1. SN 1994D appears in "
        "Pantheon+SH0ES.dat as `1994DRichmond` (photometry-source "
        "suffix); the original factory's exact-string match missed it. "
        "Fixed via suffix-tolerant CID matching in commit `5915b12`.\n"
        "- **Category C** (schema mismatch): 5 SNe per case (1980N, "
        "1981D, 2006dd in NGC 1316; 2007on, 2011iv in NGC 1404). These "
        "are present in Pantheon+SH0ES.dat with valid `m_b_corr` but "
        "flagged `IS_CALIBRATOR=0` because their hosts have no R22 "
        "Cepheid distance. The Pantheon+ flag tracks Cepheid "
        "calibration, which is orthogonal to TRGB calibration. Fixed "
        "by removing the IS_CALIBRATOR requirement in the same commit.\n\n"
        "Post-audit Pantheon+ chain coverage: Case A 16/18, Case B "
        "augmented 22/24, Case B JWST-only 11/11 (already complete). "
        "Full audit: [`host_coverage_audit.md`](host_coverage_audit.md). "
        "Genuine limitations: [`host_coverage_limitations.md`]("
        "host_coverage_limitations.md).\n\n"
    )


def _section_reproducibility() -> str:
    return (
        "## 8. Reproducibility instructions for an external reviewer\n\n"
        "An external reviewer can reconfirm every pipeline result by "
        "re-running the steps below on a fresh checkout of the "
        "repository:\n\n"
        "```bash\n"
        "git checkout <pipeline-commit-sha>\n"
        "python -m venv .venv && source .venv/bin/activate\n"
        "pip install -r requirements.txt\n"
        "\n"
        "# (a) Refresh data caches. The first call to each loader "
        "downloads\n"
        "# the underlying archive into downloaded_data/ and computes its\n"
        "# SHA-256. Pre-staged Uddin 2024 h0csp files come from a clone of\n"
        "# github.com/syeduddin/h0csp; SHA-256 manifests are recorded in\n"
        "# trgb_data/downloaded_data/uddin_h0csp/PROVENANCE.md.\n"
        "python -c 'from data.loader import DataLoader; "
        "d = DataLoader(); d.load_pantheon_plus(); "
        "d.load_pantheon_2018(); d.load_uddin_h0csp_sample(); "
        "d.load_freedman_2025_table3()'\n"
        "\n"
        "# (b) Verify SHA-256 manifests match those reported in this\n"
        "# document and in the pipeline's data_tables.tex Table 6.\n"
        "shasum -a 256 downloaded_data/pantheon_2018/lcparam_full_long.txt\n"
        "shasum -a 256 downloaded_data/pantheon_plus/Pantheon+SH0ES.dat\n"
        "shasum -a 256 trgb_data/downloaded_data/uddin_h0csp/B_trgb_update3.csv\n"
        "\n"
        "# (c) Run the pipeline. Produces the chain matrix, framework\n"
        "# predictions, analysis report, LaTeX data tables, and this\n"
        "# narrative — all from the cached + checksummed data above.\n"
        "python main.py --trgb-comparative\n"
        "```\n\n"
        "Pipeline output paths:\n\n"
        "- `results/trgb_comparative/reports/trgb_comparative_analysis_report.md` "
        "— primary analysis report with the 12-chain matrix.\n"
        "- `results/trgb_comparative/reports/data_tables.tex` — LaTeX "
        "tables of every dataset (camera-ready for the publication "
        "appendix).\n"
        "- `results/trgb_comparative/reports/data_acquisition_narrative.md` "
        "— this document.\n"
        "- `results/trgb_comparative/reports/verification_audit.md` — "
        "2026-04-24 adversarial verification audit.\n"
        "- `results/trgb_comparative/reports/host_coverage_audit.md` — "
        "2026-04-25 calibrator-coverage audit.\n"
        "- `results/trgb_comparative/reports/host_coverage_limitations.md` "
        "— Category-A data limitation documentation.\n"
        "- `trgb_data/chains/case_*_full.npz` — 12 "
        "post-audit MCMC chain files (4 SN systems × 3 cases). Each "
        "carries the full chain tensor, calibrator + flow SN names, "
        "and per-parameter R̂ diagnostics.\n"
        "- `trgb_data/prereg/trgb_comparative_preregistration_stage{1,2}.md` — "
        "two-stage preregistration documents amended for the "
        "audit-corrected methodology.\n\n"
        "If a reviewer's recomputation produces different numbers, the "
        "chain `.npz` metadata (calibrator SHA-256, MCMC walker count, "
        "step count, burn-in, seed) is sufficient to localize the "
        "divergence.\n\n"
    )


# =============================================================================
# Public renderer
# =============================================================================


def write_data_acquisition_narrative(
    loader,
    out_path: Path,
    log_fn: Optional[Callable[[str], None]] = None,
) -> Path:
    """Render the peer-review-ready data acquisition narrative to disk.

    Parameters
    ----------
    loader : DataLoader
        Pipeline-wide DataLoader instance. Live SHA-256 / file metadata
        come from this; missing datasets cause that dataset's section
        to render a `_(unavailable)_` placeholder instead of aborting.
    out_path : Path
        Output filename, e.g.
        ``results/trgb_comparative/reports/data_acquisition_narrative.md``.
    log_fn : callable, optional
        Logger callback for progress messages.
    """
    log = log_fn or (lambda m: logger.info(m))
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    parts = [
        "# Data acquisition narrative — TRGB comparative pipeline\n\n",
        f"*Generated {_now()} by `pipeline.trgb_comparative.data_acquisition_narrative`. "
        "SHA-256 values and file counts reflect the contents of `trgb_data/catalogs/` "
        "and `downloaded_data/` at generation time.*\n\n",
        _section_overview(),
        _section_anchors(loader),
        _section_trgb_tables(loader),
        _section_sn_samples(loader),
        _section_hoyt(loader),
        _section_auxiliary(),
        _section_audit_summary(),
        _section_reproducibility(),
        "## 9. References\n\n"
        "Full BibTeX records for every reference cited above are tabulated "
        "in [`data_tables.tex`](data_tables.tex) §6. The DOI / arXiv "
        "identifiers in this narrative resolve to the same papers and "
        "can be cross-referenced against that bibliography.\n",
    ]

    out_path.write_text("".join(parts))
    log(f"Data acquisition narrative → {out_path}")
    return out_path


__all__ = ["write_data_acquisition_narrative"]
