"""12-chain reproduction matrix CSV writer.

Produces ``results/12_chain_matrix.csv`` (or whatever path is passed) — a
publication-ready tabular dump of the per-(case, system) MCMC posteriors
side-by-side with the framework prediction for the corresponding anchor.

Columns:

- ``case``, ``system``, ``mode``: chain identifier and likelihood family.
- ``cal_requested``, ``cal_matched``, ``n_flow``: calibrator coverage.
- ``H0_median``, ``H0_sigma``, ``H0_lo``, ``H0_hi``: 16/50/84-percentile
  posterior summary.
- ``rhat_max``, ``converged``: Gelman-Rubin convergence diagnostics.
- ``published_target_H0`` and ``published_sigma_stat`` /
  ``published_sigma_sys``: the Freedman-paper-published target value
  and tolerance (Case A: 69.8 ± 0.8 ± 1.7; Case B aug: 70.39 ± 1.22 ±
  1.33; Case B JWST-only: 68.81 ± 1.80 — labelled sensitivity variant).
- ``delta_vs_target`` and ``within_pm_stat``: the chain's offset from
  the published target and whether it sits within the ±1σ_stat band
  (the audit's pass criterion).
- ``framework_H0_median``, ``framework_sigma``: the
  ``FrameworkMethodology.predict()`` H₀ posterior for the chain's
  anchor (LMC for Case A; NGC 4258 for both Case B variants).
- ``tension_sigma_stat_only``: framework-vs-MCMC tension in σ units,
  ``|H₀_MCMC − H₀_framework| / sqrt(σ²_MCMC + σ²_framework)``.
- ``framework_breakdown_flagged``: ``YES`` whenever
  ``|γ/H · L| ≥ 1`` (the post-2026-04-25 linear-form criterion;
  does not fire for any realistic distance-ladder anchor).

The file is written every pipeline run from the live chain matrix and
the framework predictions; no special-case code path. Generated by
``TRGBComparativePipeline.run()`` immediately after the framework
predictions are computed.
"""

from __future__ import annotations

import csv
import logging
from pathlib import Path
from typing import Any, Callable, Dict, Optional

logger = logging.getLogger(__name__)

CASES = ("case_a", "case_b", "case_b_jwst_only")
SYSTEMS = ("csp_i", "csp_ii", "supercal", "pantheon_plus")


def write_twelve_chain_matrix(
    full_calibrator_chains: Dict[str, Dict[str, Dict[str, Any]]],
    framework_a,
    framework_b,
    out_path: Path,
    log_fn: Optional[Callable[[str], None]] = None,
) -> Path:
    """Render the 12-chain matrix CSV and write it to disk.

    Parameters
    ----------
    full_calibrator_chains :
        ``{case_id: {system_id: chain_result_dict}}`` from
        :py:meth:`TRGBComparativePipeline.run_full_calibrator_matrix`.
        Each ``chain_result_dict`` carries ``H0_median``, ``H0_sigma``,
        ``H0_lo``, ``H0_hi``, ``rhat_max`` (or ``rhat_H0``),
        ``converged``, ``published_target_H0``, ``published_sigma_stat``,
        ``published_sigma_sys``, ``mode``, ``n_calibrators_requested``,
        ``n_calibrators_matched``, and ``n_flow``.
    framework_a, framework_b :
        :py:class:`FrameworkPrediction` objects for the LMC and NGC 4258
        anchors respectively. Case A and Case-B JWST-only chains use the
        respective anchor's framework prediction; Case B (24-SN augmented)
        uses the NGC 4258 prediction.
    out_path :
        Output filename, e.g. ``results/12_chain_matrix.csv``. Parent
        directory is created if missing.
    log_fn :
        Logger callback for progress messages.

    Returns
    -------
    Path
        The path written.
    """
    log = log_fn or (lambda m: logger.info(m))
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    fw_per_anchor = {
        "case_a": framework_a,
        "case_b": framework_b,
        "case_b_jwst_only": framework_b,
    }

    header = [
        "case", "system", "mode",
        "cal_requested", "cal_matched", "n_flow",
        "H0_median", "H0_sigma", "H0_lo", "H0_hi",
        "rhat_max", "converged",
        "published_target_H0", "published_sigma_stat", "published_sigma_sys",
        "delta_vs_target", "within_pm_stat",
        "framework_H0_median", "framework_sigma",
        "tension_sigma_stat_only", "framework_breakdown_flagged",
    ]

    with out_path.open("w", newline="") as fh:
        writer = csv.writer(fh)
        writer.writerow(header)
        for case in CASES:
            systems = full_calibrator_chains.get(case, {})
            fw = fw_per_anchor[case]
            if fw is None:
                continue
            fw_med = float(fw.H0_median)
            fw_sigma = 0.5 * (float(fw.H0_high) - float(fw.H0_low))
            fw_breakdown = float(fw.breakdown_fraction) > 0.5
            for system in SYSTEMS:
                rec = systems.get(system, {})
                if "H0_median" not in rec:
                    # Skipped/failed chain: emit a placeholder row so the
                    # CSV always has 12 entries (3 cases × 4 systems).
                    writer.writerow([
                        case, system, rec.get("mode", ""),
                        rec.get("n_calibrators_requested", ""),
                        rec.get("n_calibrators_matched", ""),
                        rec.get("n_flow", ""),
                        "", "", "", "",
                        "", "ERROR",
                        rec.get("published_target_H0", ""),
                        rec.get("published_sigma_stat", ""),
                        rec.get("published_sigma_sys", ""),
                        "", "",
                        f"{fw_med:.4f}", f"{fw_sigma:.4f}",
                        "", "YES" if fw_breakdown else "NO",
                    ])
                    continue
                H0 = float(rec["H0_median"])
                sigma = float(rec["H0_sigma"])
                tgt = float(rec.get("published_target_H0", 0.0))
                tol_stat = float(rec.get("published_sigma_stat", 0.0))
                tol_sys = float(rec.get("published_sigma_sys", 0.0))
                delta = H0 - tgt
                within = abs(delta) <= tol_stat
                denom = (sigma * sigma + fw_sigma * fw_sigma) ** 0.5
                tau = abs(H0 - fw_med) / denom if denom > 0 else float("nan")
                rhat = float(rec.get("rhat_max",
                                     rec.get("rhat_H0", float("nan"))))
                writer.writerow([
                    case, system, rec.get("mode", ""),
                    rec.get("n_calibrators_requested", ""),
                    rec.get("n_calibrators_matched", ""),
                    rec.get("n_flow", ""),
                    f"{H0:.4f}", f"{sigma:.4f}",
                    f"{float(rec.get('H0_lo', float('nan'))):.4f}",
                    f"{float(rec.get('H0_hi', float('nan'))):.4f}",
                    f"{rhat:.4f}",
                    "YES" if rec.get("converged") else "NO",
                    f"{tgt:.4f}", f"{tol_stat:.4f}", f"{tol_sys:.4f}",
                    f"{delta:+.4f}",
                    "YES" if within else "NO",
                    f"{fw_med:.4f}", f"{fw_sigma:.4f}",
                    f"{tau:.3f}",
                    "YES" if fw_breakdown else "NO",
                ])

    log(f"12-chain matrix → {out_path}")
    return out_path


__all__ = ["write_twelve_chain_matrix"]
