"""
ExpansionPipeline — orchestrates the full expansion-enhancement test.

Steps:
    1. Load DESI DR1 BAO, Pantheon+SH0ES, Planck 2018 θ* via ``data/loader.py``.
    2. Run emcee for each of Model A / B_const / B_qtep.
    3. Generate residual, H(z), corner, and χ² bar plots.
    4. Write a markdown + JSON summary with the falsifiability verdict.

Context flags (from main.py):
    ``short``   — use ``MCMCSettings.short()`` (fast smoke run).
    ``models``  — list of model names to run (default: all three).
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Optional

import numpy as np

from data.loader import DataLoader

from ..common.base_pipeline import AnalysisPipeline
from .data_loaders import ExpansionDataBundle, load_all
from .likelihood import (
    MODEL_A,
    MODEL_B_CONST,
    MODEL_B_QTEP,
    MODEL_B_RESIDUALS,
    ModelConfig,
    chi2_total,
)
from .mcmc_runner import MCMCResult, MCMCSettings, run_model
from .reporter import write_summary
from .visualization import generate_all_figures


_ALL_MODELS: List[ModelConfig] = [
    MODEL_A,
    MODEL_B_CONST,
    MODEL_B_QTEP,
    MODEL_B_RESIDUALS,
]


class ExpansionPipeline(AnalysisPipeline):
    """Zeno-expansion-enhancement falsifiability test."""

    def __init__(self, output_dir: str = "results"):
        super().__init__("expansion_enhancement", output_dir)
        self.update_metadata("description", "Joint BAO+SN+CMB test of framework H(z) enhancement")
        self.update_metadata("models", [m.name for m in _ALL_MODELS])

    # ------------------------------------------------------------------ run

    def run(self, context: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        ctx = context or {}
        short = bool(ctx.get("short", False))
        model_names = ctx.get("models") or [m.name for m in _ALL_MODELS]
        settings = MCMCSettings.short() if short else MCMCSettings()

        self.log_progress(f"Starting expansion-enhancement test (short={short})")
        self.log_progress(f"Models: {model_names}; MCMC: "
                          f"{settings.n_walkers}w × {settings.n_steps}s (burn-in {settings.n_burnin})")

        # --- Data ----------------------------------------------------------
        loader = DataLoader(log_file=self.log_file)
        self.log_progress("Loading BAO, SN, and CMB datasets…")
        bundle = load_all(loader)
        self.log_progress(
            f"Loaded: BAO={bundle.bao.value.size}, SN={bundle.sn.z.size}, "
            f"CMB D_M(z*)={bundle.cmb.D_M_z_rec:.1f} Mpc"
        )

        # --- MCMC per model ------------------------------------------------
        chains_dir = self.base_output_dir / "chains"
        configs: List[ModelConfig] = [m for m in _ALL_MODELS if m.name in model_names]
        results: List[MCMCResult] = []
        for cfg in configs:
            chain_path = chains_dir / f"model_{cfg.name}.npz"
            result = run_model(cfg, bundle, settings, chain_out_path=chain_path, log_fn=self.log_progress)
            results.append(result)

        # --- Figures -------------------------------------------------------
        self.log_progress("Rendering figures…")
        figure_paths = generate_all_figures(bundle, configs, results, self.figures_dir)

        # --- Report --------------------------------------------------------
        self.log_progress("Writing markdown summary…")
        report_path = write_summary(bundle, configs, results, figure_paths, self.reports_dir)
        self.log_progress(f"Report written → {report_path}")

        # Full results struct → save_results JSON.
        results_dict: Dict[str, Any] = {
            "main": {
                "n_data": bundle.n_data,
                "models": {r.model_name: r.as_dict() for r in results},
                "figures": {k: str(v) for k, v in figure_paths.items()},
                "report": str(report_path),
            },
            "settings": {
                "n_walkers": settings.n_walkers,
                "n_steps": settings.n_steps,
                "n_burnin": settings.n_burnin,
                "short": short,
            },
        }
        self.results = results_dict
        self.save_results(results_dict)
        return results_dict

    # ------------------------------------------------------- validate

    def validate(self, context: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """Light validation: check ΛCDM limit and covariance sanity.

        The substantive scientific assessment lives in the markdown summary
        generated by ``run()``; ``validate()`` is a quick self-check.
        """
        bundle = load_all()
        # Pick the model-A best-fit at its central-prior values just as a smoke.
        from .cosmology import H_LCDM, H_framework, make_H_callable
        from .likelihood import log_posterior

        theta = np.array([67.4, 0.315])
        lp = log_posterior(theta, MODEL_A, bundle)
        lcdm_limit_ok = bool(
            np.isclose(H_framework(0.5, 67.4, 0.315, 0.0, "constant"), H_LCDM(0.5, 67.4, 0.315))
        )
        # Positive-definite covariance on BAO + SN + CMB variance > 0.
        bao_pd = bool(np.all(np.linalg.eigvalsh(bundle.bao.cov) > -1e-12))
        sn_pd = bool(np.all(np.linalg.eigvalsh(bundle.sn.cov) > -1e-12))

        out = {
            "validation": {
                "lcdm_limit_ok": lcdm_limit_ok,
                "bao_cov_psd": bao_pd,
                "sn_cov_psd": sn_pd,
                "log_posterior_central": float(lp),
                "n_data": bundle.n_data,
            }
        }
        return out

    def validate_extended(self, context: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """Extended validation: very short MCMC, confirm ε=0 limit recovers Model A."""
        settings = MCMCSettings.short()
        bundle = load_all()
        r_A = run_model(MODEL_A, bundle, settings, log_fn=self.log_progress)
        r_B = run_model(MODEL_B_CONST, bundle, settings, log_fn=self.log_progress)
        # At the ε=0 boundary Model B should approximately match Model A's χ².
        chi2_A = r_A.best_fit_chi2["total"]
        chi2_B = r_B.best_fit_chi2["total"]
        # They won't be identical (r_d differs), but the difference is a sanity check.
        return {
            "validation_extended": {
                "short_chi2_A": chi2_A,
                "short_chi2_B_const": chi2_B,
                "delta_chi2": chi2_B - chi2_A,
                "r_hat_A_max": max(r_A.r_hat.values()),
                "r_hat_B_max": max(r_B.r_hat.values()),
                "n_walkers": settings.n_walkers,
                "n_steps": settings.n_steps,
            }
        }
